service: vpc-practice

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  profile: AyanD

custom:
  vpcName: practiceVPC
  igwName: practiceIGW
  publicSubnet: myPublicSubnet

resources:
  Resources:
    myVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsSupport: 'true'
        EnableDnsHostnames: 'true'
        Tags:
          - Key: Name
            Value: ${self:custom.vpcName}
    myInternetGateway:
      Type: AWS::EC2::InternetGateway
      Properties:
        Tags:
          - Key: Name
            Value: ${self:custom.igwName}
    igwAttachment:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        VpcId:
          Ref: myVPC
        InternetGatewayId:
          Ref: myInternetGateway
    publicSubnet:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Ref: myVPC
        CidrBlock: 10.0.0.0/24
        AvailabilityZone: "us-east-1a"
        Tags:
          - Key: Name
            Value: ${self:custom.publicSubnet}
    publicRouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId:
          Ref: myVPC
        Tags:
          - Key: Name
            Value: publicRouteTable
    publicSubnetInternetRoute:
      Type: AWS::EC2::Route
      Properties:
        RouteTableId:
          Ref: publicRouteTable
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId:
          Ref: myInternetGateway
    publicSubnetRouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId:
          Ref: publicRouteTable
        SubnetId:
          Ref: publicSubnet
    myNACL:
      Type: AWS::EC2::NetworkAcl
      Properties:
        VpcId:
          Ref: myVPC
        Tags:
          - Key: Name
            Value: SSHNACL
    sshNACLInboundRule:
      Type: AWS::EC2::NetworkAclEntry
      Properties:
        NetworkAclId:
          Ref: myNACL
        RuleNumber: 100
        Protocol: 6
        RuleAction: allow
        CidrBlock: 0.0.0.0/0
        PortRange:
          From: 22
          To: 22
    sshNACLOutboundRule:
      Type: AWS::EC2::NetworkAclEntry
      Properties:
        NetworkAclId:
          Ref: myNACL
        RuleNumber: 100
        Protocol: -1
        Egress: true
        RuleAction: allow
        CidrBlock: 0.0.0.0/0
    publicSubnetNetworkACLAssociation:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties:
        SubnetId:
          Ref: publicSubnet
        NetworkAclId:
          Ref: myNACL
